language: node_js
node_js:
 - "4"
 - "5"
 - "6"
 - "7"
 - "8"
cache:
  directories:
    - "node_modules"
before_script:
  - npm i mocha
  - node_version=$(node -e "console.log(/^v(\d+)/.exec(process.version)[1])")
  - if [[ $node_version > 3 ]]; then npm install express; fi
  - if [[ $node_version > 6 ]]; then npm install koa; fi
script:
  - if [[ $node_version > 3 ]]; then npm run test:express; fi
  - if [[ $node_version > 6 ]]; then npm run test:koa; fi